<a href="https://colab.research.google.com/github/ShivendraSahu22/PYTHON-CODES/blob/main/NUMPY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ARRAY_OBJECT

COPIES AND VIEWS

In [ ]:

import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a
#eventhough we modified b, it updated 'a' because both shares memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,c)

False

In [ ]:
c [0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

FANCY INDEXING

Using Boolean Mask

In [ ]:
a = np.random.randint(0,20,15)
a

array([19,  5,  2,  6, 17, 10, 12, 16,  6, 19, 15,  4,  6,  0, 11])

In [ ]:
mask = (a % 2 == 0)

In [ ]:
extract_from_a = a[mask]
extract_from_a

array([ 2,  6, 10, 12, 16,  6,  4,  6,  0])

In [14]:
mask = (a % 2 == 0)
mask

array([False, False,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True, False])

INDEXING with a mask can be very useful to assign a new value to a sub array

In [15]:
a[mask] = -1
a

array([19,  5, -1, -1, 17, -1, -1, -1, -1, 19, 15, -1, -1, -1, 11])

In [18]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [21]:
#new values can be assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

THE NUMPY ARRAY OBJECT

NUMPY ARRAYS

python object

In [ ]:
import numpy as np

Elementwise operations

In [24]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [25]:
a**2

array([ 1,  4,  9, 16])

All arithmetic operators elementwise

In [30]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

In [29]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [26]:
b = np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [31]:
b = np.ones(4)+1
a*b

array([2., 4., 6., 8.])

In [35]:
#Matrix Multiplication
c = np.diag([1,2,3,4])
print(c*c)
print("***************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [37]:
a = ([1,2],[3,4])
a[1*1]

[3, 4]

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [39]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [41]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,c)

True

In [42]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [43]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
np.logical_and(a,b)

array([ True, False, False, False])

Transcendental functions :

In [44]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [46]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [47]:
np.log(a)

/tmp/ipython-input-176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [50]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [69]:
a = np.arange(4)
a + np.array([1,2,3,4])

array([1, 3, 5, 7])

Computing Sum

In [53]:
x = np.array([1,2,3,4])
np.sum(x)

np.int64(10)

In [54]:
x.sum(axis=0)

np.int64(10)

In [57]:
x =np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [58]:
x.sum(axis=1) #rows second dimension

array([2, 4])

In [59]:
x = np.array([1,3,2])
x.min()

np.int64(1)

In [60]:
x.max()

np.int64(3)

In [61]:
x.argmin()  #index of minimum element

np.int64(0)

In [63]:
x.argmax() #index of maximum element

np.int64(1)

In [64]:
np.all([True,True,False])

np.False_

In [65]:
np.any([True,False,False])

np.True_

In [67]:
a = np.zeros((50,50))
np.any(a!=0)

np.False_

In [68]:
np.all(a==0)

np.True_