<a href="https://colab.research.google.com/github/ShivendraSahu22/PYTHON-CODES/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


Python List

In [5]:
L = range(1000)
%timeit [i**2 for i in L]

84.4 µs ± 26.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Using Numpy

In [9]:
import numpy as np
a = np.arange(1000)
%timeit a**2

2.42 µs ± 85.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Manual Construction Of Array

In [12]:
#1-D

import numpy as np

a = np.array([0,1,2,3])

a

array([0, 1, 2, 3])

Find

In [ ]:

#print dimension
a.ndim

In [20]:
#print Shape
a.shape

(4,)

In [13]:

#print lenght
len(a)

4

Question

In [18]:
import numpy as np
s = np.array([0,1,2,3,4,5])
s

array([0, 1, 2, 3, 4, 5])

In [17]:
s.ndim

1

In [16]:
len(s)

6

In [19]:
s.shape

(6,)

2D,3D ARRAY

In [41]:
#2-D,3-D..
import numpy as np
b = ([[0,1,2,3],[4,5,7]])
b

[[0, 1, 2, 3], [4, 5, 6, 7]]

In [ ]:
b.shape

In [38]:
len(b)

2

In [ ]:
b.ndim

QUESTION

In [46]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
len(c)

2

In [48]:
c.ndim

3

In [50]:
c.shape

(2, 2, 2)

FUNCTION TO CREATE ARRAY

In [58]:
#using arange function
#arange is an array-valued version of the build-in python create arange function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b = np.arange(1,2,3) #start,end (exclusive),step
b

array([1])

In [59]:
#using linspace ,leineare space
a = np.linspace(0,1,6)#start,end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [60]:
#common array
#1
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
#common array
#0
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
c = np.eye(3) # Return a 2-D array with ones in the diagonal
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
d = np.eye(3,2) #3 is number of rows, 2 is number of columns
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [65]:

#create array using diag function
a = np.diag([1,2,3,4]) #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [66]:
np.diag(a) #Extract diagonal

array([1, 2, 3, 4])

In [67]:
#Create array using random
#Create an array of the given shape and populate it with random
a = np.random.rand(4)
a

array([0.1832565 , 0.14354714, 0.70287824, 0.56066418])

In [70]:
a = np.random.randn(4)
a

array([0.46578627, 1.01393377, 0.10210017, 0.72659556])

In [72]:
a = np.arange(10)
a.dtype

dtype('int64')

In [73]:
#You can explicitly specify which data-type you want:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
#The default data type is float zeros and ones function
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

Other datatype

In [75]:
d = np.array([1+2j,2+4j]) #complex datatype
print(d.dtype)

complex128


In [79]:
b = np.array([True,False,True,False]) #boolean datatype
print(b.dtype)

bool


In [84]:
s = np.array(['Ram', 'Robert', 'Raheem'])
s.dtype

dtype('<U6')

INDEXING AND SLICING

In [87]:
a = np.arange(10)
print(a[5])

5


In [88]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [89]:
a[2,1] = 5 # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])