<a href="https://colab.research.google.com/github/ShivendraSahu22/PYTHON-CODES/blob/main/NUMPY3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical Operations on array

In [ ]:

import numpy as np
np.all([True,true,False])

In [ ]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

np.True_

STATISTICS

In [ ]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

np.float64(1.75)

MEAN

In [ ]:
y.mean()

np.float64(3.0)

Median

In [ ]:
np.median(x)

np.float64(1.5)

In [ ]:
np.median(y)

np.float64(2.5)

In [ ]:
np.median(y,axis=-1)

array([2., 5.])

STANDARD DEVIATIONS

In [ ]:
x.std()

np.float64(0.82915619758885)

In [ ]:
y.std()

np.float64(1.9148542155126762)

In [ ]:
y.std(axis = 1)

array([0.81649658, 2.1602469 ])

In [ ]:
y.std(axis = 0)

array([2., 2., 1.])

Load data

In [ ]:
data = np.loadtxt('population.txt')
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [ ]:
year,hares,lynxes,carrots = data.T #columns
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [ ]:
#The mean population over time
populations = data[:,1:]
print(populations)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [ ]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [ ]:
std = populations.std(axis=1)
print(std)

[18176.23601177 19614.67704439 24668.33327703 19225.21492439
 10030.73055941  9530.41913501  9458.79954798 12319.18106946
 14923.434219   13472.52347888 15759.51211879 16967.22330456
 18751.53327064 23553.39088586  5266.87763291 13018.02169644
 10757.4263754  14578.82787546 14819.88154099 13501.68713737
 15873.31793363]


In [ ]:
np.argmax(populations,axis =1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [ ]:
np.argmax(populations,axis =0)

array([3, 4, 0])

BROADCASTING

In [ ]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [ ]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("*******†********")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*******†********
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:

a = np.tile(np.arange(0,40,10),(3,2))
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [ ]:
a = np.tile(np.arange(0,40,10),(3,2))
print(a)
print("*******†********")
a = a.T
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
*******†********
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
b = np.arange(0,1,2)
a+b

In [ ]:
a = np.arange(0,40,10)
a.shape

In [ ]:
a = np.arange(0,40,10)
a = a[:,np.newaxis] # adds a new axis ->20
a.shape

In [ ]:
a

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [ ]:
a + b