<a href="https://colab.research.google.com/github/ShivendraSahu22/PYTHON-CODES/blob/main/NUMPY4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical Operations on array

In [ ]:
import numpy as np
a = np.arange(0,40,10)
a.shape

(4,)

In [ ]:
a = np.arange(0,40,10)
a = a[:,np.newaxis] # adds a new axis ->20
a.shape

(4, 1)

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np.arange(0,1,2)

In [ ]:
a+b

array([[ 0],
       [10],
       [20],
       [30]])

Flettening

In [ ]:

#2d into 1d
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [ ]:
a.shape

(2, 3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [ ]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0][0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
b.ravel()

array([100,   2,   3,   4,   5,   6])

In [ ]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [ ]:
z.ravel()

array([1, 2, 3])

In [ ]:
z = z.T
z

array([1, 2, 3])

In [ ]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

Dimension Shuffling

In [ ]:
a = np.arange(4*3*2).reshape(4,3,2)
a
a.shape

(4, 3, 2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [32]:
a[0,2,1]

np.int64(5)

Resizing

In [37]:
a[2,1,1]

np.int64(15)

In [38]:
a = np.arange(4)
a.resize(8,)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [39]:
a = np.arange(4)
a.resize(8,3)
        #row, column
a

array([[0, 1, 2],
       [3, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:

a = np.arange(4)
a.resize(8,5)
a

array([[0, 1, 2, 3, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
b = a
a.resize((4,))

In [43]:
a = np.array([[5,6,4],[4,3,4]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [3, 4, 4]])

In [49]:

a = np.array([[5,6,4],[4,3,4]])
b = np.sort(a,axis=0)
b

array([[4, 3, 4],
       [5, 6, 4]])

In [48]:
a = np.array([[5,6,4],[4,3,4]])
b = np.sort(a,axis=1)[:, ::-1] # Sorts in descending order
b

array([[6, 5, 4],
       [4, 4, 3]])

In [50]:
a = np.array([[5,6,4],[4,3,4]])
b = np.sort(a,axis=1)[:, ::1] # Sorts in ascending order
b

array([[4, 5, 6],
       [3, 4, 4]])

In [51]:
a = np.array([4,3,1,2])
s = np.argsort(a)
s

array([2, 3, 1, 0])

In [54]:
a[s]

array([1, 2, 3, 4])